@extends('reports.layouts.base')

@section('title', 'Institutional Base Report - ' . ($reportConfig['org_name'] ?? 'DoorKnob'))

@section('document-title', $documentTitle ?? 'INSTITUTIONAL PERFORMANCE & ACADEMIC AUDIT REPORT')
@section('document-subtitle', $documentSubtitle ?? 'Comprehensive Evaluation & Multi-Class Summary')
@section('document-number', $docNumber ?? 'REP-' . date('Ymd') . '-001')
@section('document-date', $reportDate ?? date('d M Y'))
@section('document-session', $sessionName ?? '2026-2027 Academic Session')

@section('content')

{{-- Top Key Performance Indicators --}}
<div class="kpi-row">
    <div class="kpi-card">
        <div class="kpi-title">Total Enrolled Students</div>
        <div class="kpi-value">{{ $totalStudents ?? '1,250' }}</div>
    </div>
    <div class="kpi-card">
        <div class="kpi-title">Average Attendance</div>
        <div class="kpi-value text-success">{{ $avgAttendance ?? '94.8%' }}</div>
    </div>
    <div class="kpi-card">
        <div class="kpi-title">Fee Collection Rate</div>
        <div class="kpi-value text-success">{{ $feeCollectionRate ?? '96.2%' }}</div>
    </div>
    <div class="kpi-card">
        <div class="kpi-title">Academic Pass Rate</div>
        <div class="kpi-value text-success">{{ $academicPassRate ?? '98.5%' }}</div>
    </div>
</div>

{{-- Institutional Context & Scope --}}
<div class="info-grid">
    <div class="info-box">
        <div class="info-box-title">Institutional Information</div>
        <div class="info-row">
            <span class="info-label">Institution:</span>
            <span class="info-value">{{ $reportConfig['org_name'] }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Affiliation / Code:</span>
            <span class="info-value">{{ $reportConfig['affiliation_number'] ?: 'CBSE-99824' }} ({{ $reportConfig['school_code'] ?: 'SCH-010' }})</span>
        </div>
        <div class="info-row">
            <span class="info-label">Academic Session:</span>
            <span class="info-value">{{ $sessionName ?? 'Current Session' }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Report Category:</span>
            <span class="info-value">Administrative & Financial Audit</span>
        </div>
    </div>

    <div class="info-box">
        <div class="info-box-title">Audit Metadata</div>
        <div class="info-row">
            <span class="info-label">Report Reference:</span>
            <span class="info-value">{{ $docNumber ?? 'REP-' . date('Ymd') . '-001' }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generation Mode:</span>
            <span class="info-value">{{ $isPdfRender ? 'BrowserShot Headless PDF' : 'Interactive Web Preview' }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated By:</span>
            <span class="info-value">{{ Auth::check() ? Auth::user()->first_name . ' ' . Auth::user()->last_name : 'System Administrator' }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Status:</span>
            <span class="info-value text-success">Verified & Approved</span>
        </div>
    </div>
</div>

{{-- Class Performance & Enrollment Table --}}
<table class="report-table">
    <thead>
        <tr>
            <th style="width: 6%;">#</th>
            <th style="width: 24%;">Class & Section</th>
            <th style="width: 15%; text-align: center;">Students</th>
            <th style="width: 15%; text-align: center;">Attendance</th>
            <th style="width: 20%; text-align: right;">Fee Expected</th>
            <th style="width: 20%; text-align: right;">Fee Collected</th>
        </tr>
    </thead>
    <tbody>
        @php
            $sampleRows = $tableRows ?? [
                ['class' => 'Class 10 - Section A', 'students' => 42, 'att' => '96.2%', 'expected' => 420000, 'collected' => 415000],
                ['class' => 'Class 10 - Section B', 'students' => 40, 'att' => '95.0%', 'expected' => 400000, 'collected' => 392000],
                ['class' => 'Class 9 - Section A',  'students' => 45, 'att' => '93.8%', 'expected' => 405000, 'collected' => 395000],
                ['class' => 'Class 9 - Section B',  'students' => 44, 'att' => '94.5%', 'expected' => 396000, 'collected' => 388000],
                ['class' => 'Class 8 - Section A',  'students' => 38, 'att' => '97.1%', 'expected' => 342000, 'collected' => 340000],
                ['class' => 'Class 8 - Section B',  'students' => 39, 'att' => '92.4%', 'expected' => 351000, 'collected' => 335000],
                ['class' => 'Class 7 - Section A',  'students' => 41, 'att' => '95.6%', 'expected' => 328000, 'collected' => 320000],
                ['class' => 'Class 6 - Section A',  'students' => 37, 'att' => '96.0%', 'expected' => 296000, 'collected' => 290000],
            ];
            $totalStudentsCount = 0;
            $totalExp = 0;
            $totalCol = 0;
        @endphp

        @foreach($sampleRows as $index => $row)
            @php
                $totalStudentsCount += $row['students'];
                $totalExp += $row['expected'];
                $totalCol += $row['collected'];
            @endphp
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td class="fw-bold">{{ $row['class'] }}</td>
                <td class="text-center">{{ $row['students'] }}</td>
                <td class="text-center">{{ $row['att'] }}</td>
                <td class="text-right">₹{{ number_format($row['expected'], 2) }}</td>
                <td class="text-right text-success fw-bold">₹{{ number_format($row['collected'], 2) }}</td>
            </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2" class="fw-bold">Consolidated Totals</td>
            <td class="text-center fw-bold">{{ $totalStudentsCount }} Students</td>
            <td class="text-center fw-bold">95.1% Avg</td>
            <td class="text-right fw-bold">₹{{ number_format($totalExp, 2) }}</td>
            <td class="text-right text-success fw-bold">₹{{ number_format($totalCol, 2) }}</td>
        </tr>
    </tfoot>
</table>

{{-- Institutional Notice / Verification Note --}}
<div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 4px; padding: 10px 14px; font-size: 11px; color: #475569; margin-bottom: 10px;">
    <strong>Verification & Compliance Notice:</strong>
    This document serves as an official institutional record generated directly from the {{ $reportConfig['org_name'] }} Educational Management Engine. All figures, student counts, and fee summaries have been reconciled against the primary database ledger. For verification inquiries, contact the administrative office at {{ $reportConfig['phone'] ?: 'N/A' }} or via email at {{ $reportConfig['email'] ?: 'N/A' }}.
</div>

@endsection
