<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\ReportEngineService;
use App\Services\SettingService;
use App\Models\SchoolSession;
use App\Models\SchoolClass;
use App\Interfaces\SchoolSessionInterface;
use App\Traits\SchoolSession as SchoolSessionTrait;
use Illuminate\Support\Facades\Auth;

class ReportEngineController extends Controller
{
    use SchoolSessionTrait;

    /**
     * @var ReportEngineService
     */
    protected $reportEngine;

    /**
     * @var SettingService
     */
    protected $settingService;

    /**
     * @var SchoolSessionInterface
     */
    protected $schoolSessionRepository;

    /**
     * ReportEngineController constructor.
     *
     * @param ReportEngineService $reportEngine
     * @param SettingService $settingService
     * @param SchoolSessionInterface $schoolSessionRepository
     */
    public function __construct(
        ReportEngineService $reportEngine,
        SettingService $settingService,
        SchoolSessionInterface $schoolSessionRepository
    ) {
        $this->middleware(['auth']);
        $this->reportEngine = $reportEngine;
        $this->settingService = $settingService;
        $this->schoolSessionRepository = $schoolSessionRepository;
    }

    /**
     * Interactive HTML Web Preview of the Base / Letterhead Report.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\View
     */
    public function previewBaseReport(Request $request)
    {
        $data = $this->buildSampleReportData($request);
        $data['pdfDownloadUrl'] = route('reports.base.pdf', $request->query());

        return $this->reportEngine->preview('reports.templates.sample-base-report', $data);
    }

    /**
     * Download Base Report as a PDF generated by BrowserShot.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function downloadBaseReportPdf(Request $request)
    {
        $data = $this->buildSampleReportData($request);
        $filename = 'base_institutional_report_' . date('Y-m-d_His') . '.pdf';

        return $this->reportEngine->downloadPdf(
            'reports.templates.sample-base-report',
            $data,
            $filename
        );
    }

    /**
     * Stream Base Report PDF directly in browser via BrowserShot.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function streamBaseReportPdf(Request $request)
    {
        $data = $this->buildSampleReportData($request);
        $filename = 'base_institutional_report_' . date('Y-m-d_His') . '.pdf';

        return $this->reportEngine->streamPdf(
            'reports.templates.sample-base-report',
            $data,
            $filename
        );
    }

    /**
     * Live Preview iframe endpoint embedded inside Super Admin Settings.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\View
     */
    public function settingsPreview(Request $request)
    {
        $user = Auth::user();
        if (!$user || !$user->isSuperAdmin()) {
            abort(403, 'Only Super Admin can access live report preview.');
        }

        $data = $this->buildSampleReportData($request);
        $data['pdfDownloadUrl'] = route('reports.base.pdf');

        return $this->reportEngine->preview('reports.templates.sample-base-report', $data);
    }

    /**
     * Build standard sample data for the base report.
     *
     * @param Request $request
     * @return array
     */
    protected function buildSampleReportData(Request $request): array
    {
        $sessionId = $this->getSchoolCurrentSession();
        $session = SchoolSession::find($sessionId);
        $sessionName = $session ? $session->session_name : (date('Y') . '-' . (date('Y') + 1) . ' Academic Session');

        // Retrieve real classes if available, otherwise graceful fallback
        $classes = SchoolClass::where('session_id', $sessionId)->get();
        $tableRows = [];

        if ($classes->count() > 0) {
            foreach ($classes as $index => $cls) {
                $studentCount = $cls->promotions()->count();
                $tableRows[] = [
                    'class'     => $cls->class_name,
                    'students'  => $studentCount > 0 ? $studentCount : (35 + ($index * 3)),
                    'att'       => (92 + ($index % 6)) . '.' . ($index * 2 % 9) . '%',
                    'expected'  => ($studentCount > 0 ? $studentCount : 35) * 10000,
                    'collected' => ($studentCount > 0 ? $studentCount : 35) * 9600,
                ];
            }
        } else {
            $tableRows = [
                ['class' => 'Class 10 - Section A', 'students' => 42, 'att' => '96.2%', 'expected' => 420000, 'collected' => 415000],
                ['class' => 'Class 10 - Section B', 'students' => 40, 'att' => '95.0%', 'expected' => 400000, 'collected' => 392000],
                ['class' => 'Class 9 - Section A',  'students' => 45, 'att' => '93.8%', 'expected' => 405000, 'collected' => 395000],
                ['class' => 'Class 9 - Section B',  'students' => 44, 'att' => '94.5%', 'expected' => 396000, 'collected' => 388000],
                ['class' => 'Class 8 - Section A',  'students' => 38, 'att' => '97.1%', 'expected' => 342000, 'collected' => 340000],
                ['class' => 'Class 8 - Section B',  'students' => 39, 'att' => '92.4%', 'expected' => 351000, 'collected' => 335000],
                ['class' => 'Class 7 - Section A',  'students' => 41, 'att' => '95.6%', 'expected' => 328000, 'collected' => 320000],
                ['class' => 'Class 6 - Section A',  'students' => 37, 'att' => '96.0%', 'expected' => 296000, 'collected' => 290000],
            ];
        }

        return [
            'documentTitle'     => 'INSTITUTIONAL PERFORMANCE & ACADEMIC AUDIT REPORT',
            'documentSubtitle'  => 'Standardized School Audit, Enrollment & Financial Health Statement',
            'docNumber'         => 'REP-' . date('Ymd') . '-001',
            'reportDate'        => date('d M Y'),
            'sessionName'       => $sessionName,
            'totalStudents'     => number_format(array_sum(array_column($tableRows, 'students'))),
            'avgAttendance'     => '95.2%',
            'feeCollectionRate' => '97.4%',
            'academicPassRate'  => '98.8%',
            'tableRows'         => $tableRows,
        ];
    }
}
